runtime: custom
env: flex

env_variables:
  SECRET_KEY: "YOUR_SECURE_SECRET_KEY"
  APP_PASSWORD: "your_secure_password"
  # PostgreSQL 接続用の環境変数（例）
  DATABASE_URL: "postgres://avnadmin:AVNS_455zs7zc8pmoX31bL14@pg-3dba9fd7-m0i3k911-5554.c.aivencloud.com:25604/defaultdb?sslmode=require

resources:
  cpu: 1
  memory_gb: 1
